package com.hms.pharmacy.entity;

public enum MedicineCategory {
    ANALGESICS,              // Pain relievers (e.g., ibuprofen, acetaminophen)
    ANTIBIOTICS,             // Treat bacterial infections (e.g., penicillin, amoxicillin)
    ANTIVIRALS,              // Treat viral infections (e.g., oseltamivir)
    ANTIFUNGALS,             // Treat fungal infections (e.g., fluconazole)
    ANTIPARASITICS,          // Treat parasitic infections (e.g., ivermectin)
    ANTIHISTAMINES,          // Treat allergies (e.g., cetirizine)
    ANTIDEPRESSANTS,         // Treat depression (e.g., sertraline)
    ANTIPSYCHOTICS,          // Treat psychiatric disorders (e.g., risperidone)
    ANTIHYPERTENSIVES,       // Treat high blood pressure (e.g., lisinopril)
    DIURETICS,               // Increase urine output (e.g., furosemide)
    ANTIDIABETICS,           // Manage diabetes (e.g., metformin)
    ANTICOAGULANTS,          // Prevent blood clotting (e.g., warfarin)
    ANTIPLATELETS,           // Reduce platelet aggregation (e.g., aspirin)
    STATINS,                 // Lower cholesterol (e.g., atorvastatin)
    BRONCHODILATORS,         // Treat respiratory issues (e.g., albuterol)
    CORTICOSTEROIDS,         // Reduce inflammation (e.g., prednisone)
    IMMUNOSUPPRESSANTS,      // Suppress immune response (e.g., cyclosporine)
    ANTICONVULSANTS,         // Treat seizures (e.g., levetiracetam)
    ANTIEMETICS,             // Prevent nausea and vomiting (e.g., ondansetron)
    ANTIANXIETY,             // Treat anxiety (e.g., lorazepam)
    HORMONE_THERAPY,         // Hormone-related treatments (e.g., insulin, levothyroxine)
    CHEMOTHERAPY,            // Treat cancer (e.g., paclitaxel)
    VACCINES,                // Prevent diseases (e.g., measles vaccine)
    ANESTHETICS,             // Induce anesthesia (e.g., propofol)
    ANTACIDS,                // Neutralize stomach acid (e.g., omeprazole)
    LAXATIVES,               // Relieve constipation (e.g., lactulose)
    ANTIINFLAMMATORY,        // Reduce inflammation (e.g., ibuprofen)
    SEDATIVES,               // Promote sleep or relaxation (e.g., zolpidem)
    STIMULANTS,              // Increase alertness (e.g., methylphenidate)
    VITAMINS_SUPPLEMENTS,    // Nutritional supplements (e.g., vitamin D)
    ANTITUSSIVES,            // Suppress cough (e.g., dextromethorphan)
    EXPECTORANTS,            // Promote mucus expulsion (e.g., guaifenesin)
    OPHTHALMIC,              // Treat eye conditions (e.g., latanoprost)
    DERMATOLOGICAL,          // Treat skin conditions (e.g., hydrocortisone cream)
    ANTIALLERGICS,           // Treat allergic reactions (e.g., epinephrine)
    ANTIPYRETICS,            // Reduce fever (e.g., paracetamol)
    ANTIMALARIALS,           // Treat malaria (e.g., chloroquine)
    ANTISPASMODICS           // Relieve muscle spasms (e.g., dicyclomine)
}
